### PR TITLE
Drop Node v0.8 and add io.js

### PR DESCRIPTION
**Pull request by nylen**
As requested at https://github.com/request/request-debug/pull/3#issuecomment-99131350.

The multiple `request` versions are tested to maintain backwards compatibility with older versions.  I was seeing some strange issues and this seemed like a good health check of both libraries.  I've updated the version numbers here, we could probably remove a few more from the list.

### CODE REVIEW

**Comment by nylen** [comment]
ping @simov, hopefully all these builds pass, Travis is slow today.

**Comment by nylen** [comment]
[You said](https://github.com/request/request-debug/pull/3#issuecomment-99131350):
> Also I'm not sure why do we need to test against so many versions of request.

Maybe this is more trouble than it's worth.  I forgot how much these tests sucked.

**Comment by nylen** [comment]
@simov Build passes now, but it will probably break again in the future.  How can we make these tests more robust?  A couple of ideas:

- Only test for a few specific headers
- Record requests and responses for each Node/io.js and `request` version, and store them separately (how to automate this?)

**Comment by simov** [comment]
Only test for a few specific headers might be the better option. Btw why not put the contents of the `maybeTransferEncodingChunked` function into `lib/fixHeader`? If I'm understanding correctly you are already doing some header manipulations there.

**Comment by nylen** [comment]
Sure, you could delete that header with a function that returns `null`.  Then it wouldn't be checked, which is probably OK.

**Comment by simov** [comment]
@nylen I just converted to 2 space indentation to mach the rest of projects in this organization. I decided to leave `maybeTransferEncodingChunked` as it is because it is used only for a single and specific requests, and can't blend that well with the rest of the code in lib. If you are OK with the indentation change, we can merge it and resolve https://github.com/request/request-debug/pull/3 after that.

**Comment by nylen** [comment]
Fine with me!

**Comment by simov** [comment]
:tada: tests are passing

**Pull request merged**
